apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "deppkg-cud.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "deppkg-cud.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "deppkg-cud.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.image }} 
        image: "{{ .repository }}{{- if .digest }}@{{ .digest }}{{- else }}:{{ .tag | default $.Chart.AppVersion }}{{- end}}"
        {{- end }}
        imagePullPolicy: Always
        {{- with .Values.service }}
        ports:
          - name: {{ .portName }}
            containerPort: {{ .exposedPort }}
            protocol: TCP
        {{- end }}
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
